import Foundation
import WebKit

// サイトごとのCookieを管理し、yt-dlpが読めるNetscape形式で保存する
class CookieManager {
    static let shared = CookieManager()

    private let cookieDirectory: URL

    init() {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        cookieDirectory = appSupport.appendingPathComponent("yt-dlp-swift/cookies", isDirectory: true)
        try? FileManager.default.createDirectory(at: cookieDirectory, withIntermediateDirectories: true)
    }

    // サイトのextractorPatternに対応するcookieファイルパス
    func cookieFilePath(for extractorPattern: String) -> URL {
        let safeName = extractorPattern
            .replacingOccurrences(of: ":", with: "_")
            .replacingOccurrences(of: "/", with: "_")
        return cookieDirectory.appendingPathComponent("\(safeName).txt")
    }

    // cookieファイルが存在するか
    func hasCookies(for extractorPattern: String) -> Bool {
        FileManager.default.fileExists(atPath: cookieFilePath(for: extractorPattern).path)
    }

    // 全サイト共通のcookieファイル (複数サイトのcookieをマージ)
    var mergedCookieFilePath: URL {
        cookieDirectory.appendingPathComponent("merged_cookies.txt")
    }

    // WKWebViewのcookieストアからNetscape形式のcookieファイルを書き出す
    func exportCookies(from dataStore: WKWebsiteDataStore, for extractorPattern: String, siteURL: String?) async throws {
        let cookies = await dataStore.httpCookieStore.allCookies()

        // サイトURLのドメインに関連するcookieのみフィルタ
        let relevantCookies: [HTTPCookie]
        if let siteURL = siteURL, let url = URL(string: siteURL), let host = url.host {
            let baseDomain = extractBaseDomain(from: host)
            relevantCookies = cookies.filter { cookie in
                let cookieDomain = cookie.domain.hasPrefix(".") ? String(cookie.domain.dropFirst()) : cookie.domain
                return cookieDomain.hasSuffix(baseDomain) || baseDomain.hasSuffix(cookieDomain)
            }
        } else {
            relevantCookies = cookies
        }

        guard !relevantCookies.isEmpty else { return }

        let netscapeContent = convertToNetscapeFormat(cookies: relevantCookies)
        let filePath = cookieFilePath(for: extractorPattern)
        try netscapeContent.write(to: filePath, atomically: true, encoding: .utf8)

        // マージファイルも更新
        try rebuildMergedCookieFile()
    }

    // cookieを削除
    func removeCookies(for extractorPattern: String) throws {
        let filePath = cookieFilePath(for: extractorPattern)
        if FileManager.default.fileExists(atPath: filePath.path) {
            try FileManager.default.removeItem(at: filePath)
            try rebuildMergedCookieFile()
        }
    }

    // Netscape cookie形式に変換
    // フォーマット: domain\tinclude_subdomains\tpath\tsecure\texpiry\tname\tvalue
    private func convertToNetscapeFormat(cookies: [HTTPCookie]) -> String {
        var lines = ["# Netscape HTTP Cookie File", "# Generated by yt-dlp-swift", ""]

        for cookie in cookies {
            let domain = cookie.domain
            let includeSubdomains = domain.hasPrefix(".") ? "TRUE" : "FALSE"
            let path = cookie.path
            let secure = cookie.isSecure ? "TRUE" : "FALSE"
            let expiry: String
            if let expiresDate = cookie.expiresDate {
                expiry = String(Int(expiresDate.timeIntervalSince1970))
            } else {
                // セッションCookieの場合、遠い未来を設定
                expiry = "0"
            }
            let name = cookie.name
            let value = cookie.value

            lines.append("\(domain)\t\(includeSubdomains)\t\(path)\t\(secure)\t\(expiry)\t\(name)\t\(value)")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // 全サイトのcookieをマージして1つのファイルにまとめる
    private func rebuildMergedCookieFile() throws {
        var allLines = ["# Netscape HTTP Cookie File", "# Generated by yt-dlp-swift (merged)", ""]

        let files = try FileManager.default.contentsOfDirectory(at: cookieDirectory, includingPropertiesForKeys: nil)
        for file in files where file.pathExtension == "txt" && file.lastPathComponent != "merged_cookies.txt" {
            let content = try String(contentsOf: file, encoding: .utf8)
            for line in content.components(separatedBy: "\n") {
                if !line.hasPrefix("#") && !line.isEmpty {
                    allLines.append(line)
                }
            }
        }

        let merged = allLines.joined(separator: "\n") + "\n"
        try merged.write(to: mergedCookieFilePath, atomically: true, encoding: .utf8)
    }

    // ホスト名からベースドメインを抽出 (例: www.nicovideo.jp → nicovideo.jp)
    private func extractBaseDomain(from host: String) -> String {
        let parts = host.components(separatedBy: ".")
        if parts.count >= 2 {
            return parts.suffix(2).joined(separator: ".")
        }
        return host
    }
}
